services:
  accounts:
    image: bank-microservices/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
      - "8081:8080"
    networks:
      - bank-microservices
  cards:
    image: bank-microservices/cards:latest
    mem_limit: 700m
    ports:
      - "8082:9000"
    networks:
      - bank-microservices
  loans:
    image: bank-microservices/loans:latest
    mem_limit: 700m
    ports:
      - "8083:8090"
    networks:
      - bank-microservices
networks:
  bank-microservices: